version: '3.9'

services:
  springboot-layer:
    container_name: springbootlayer-container
    image: "demo/springbootlayer:0.0.1"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:8080"

# docker-compose up -d --build
# docker-compose build